import SupportSideNav from "@/components/Pages/SupportPage/SupportSideNav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SupportRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex h-full sm:h-[calc(100vh_-_100px)]">
      <SupportSideNav />
      <div className="panel rounded-l-none h-full flex-1 overflow-x-hidden p-0">
        <div className="flex h-full flex-col">{children}</div>
      </div>
    </div>
  );
}
